TARGET = ngx_array_test
SOURCES = ngx_array_test.c

#############################################################
include ../common.mk
#############################################################

# make all