TARGET = ngx_list_test
SOURCES = ngx_list_test.c

#############################################################
include ../common.mk
#############################################################

# make all